// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_yn3cDQuy7is4QTN_61udMaB3xnCLRNk',
    appId: '1:765657516408:web:3a876a0d6956c32009208d',
    messagingSenderId: '765657516408',
    projectId: 'project-5368672327624315569',
    authDomain: 'project-5368672327624315569.firebaseapp.com',
    storageBucket: 'project-5368672327624315569.appspot.com',
    measurementId: 'G-LF728396S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6vzSB8R9OoZukVQQTXSIUgKLiVucf10',
    appId: '1:765657516408:android:00ba6546b0662ef709208d',
    messagingSenderId: '765657516408',
    projectId: 'project-5368672327624315569',
    storageBucket: 'project-5368672327624315569.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2WCp1djkP2ss0KSYiX34sYqKuhx5aEH8',
    appId: '1:765657516408:ios:010fb9a85136573e09208d',
    messagingSenderId: '765657516408',
    projectId: 'project-5368672327624315569',
    storageBucket: 'project-5368672327624315569.appspot.com',
    iosBundleId: 'com.example.flutterCafeAdmin.RunnerTests',
  );
}
